### ISSUE TITLE
Builds fail from external PR's

### ISSUE THREAD

**Issue by jong82** [chanzuckerberg/terraform-provider-snowflake#120]
If I fork the repo and create a PR from my fork then Travis CI builds fail since it doesn't use a username/password for external PR's.
However I am getting permission denied to create a branch in this repo.  What is the proper way to create a PR that will also build?

https://travis-ci.com/chanzuckerberg/terraform-provider-snowflake/jobs/269044056#L183
```
Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
```

Feel free to close this issue if I missed something or simply not following the correct pattern to create a PR.

**Comment by ryanking** [comment]
@jong82 There is not currently an easy way to get this working, but we should fix that.

The problem is that our test suite relies on creating real resources in a test snowflake account. We use a test snowflake account which is totally separate from our production ones

But for obvious reasons, we don't want to allow anyone that can create a PR (anyone with a github account) to have access to that account.

There should be a way for those who want to submit PRs to get them to build, but this will require some investigations. I will get back to you when I have something.

**Comment by ryanking** [comment]
@jong82 I am adding a bit to the README about how to get this set up https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/122
