### ISSUE TITLE
Show incorrect differences in snowflake_schema_grants

### ISSUE THREAD

**Issue by kanata2** [chanzuckerberg/terraform-provider-snowflake#311]
**Provider Version**
0.18.1

**Terraform Version**
0.13.4

**Describe the bug**
I applied and made sure it was reflected in the console and tfstate, but the subsequent `terraform plan/apply` always shows a difference in roles like followings.

```tf
  # snowflake_schema_grant.xxxx must be replaced
-/+ resource "snowflake_schema_grant" "xxx" {
        database_name     = "XXXX"
      ~ id                = "XXXX|||ALL|false" -> (known after apply)
        on_future         = true
        privilege         = "ALL"
      ~ roles             = [ # forces replacement
          + "YYYY",
        ]
      - shares            = [] -> null
        with_grant_option = false
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

**Expected behavior**
Once you applied, there is no differences in plan/apply.

**Code samples and commands**

```tf
resource snowflake_schema_grants test {
    database_name = "TESTDB"
    on_future = true
    privilege = "ALL"
    roles = [snowflake_role.test.name]
}
```

**Additional context**
nothing

**Comment by edwinbdr** [comment]
This is also true for database grants (and probably for other types of grants as well). We are facing a similar issue.

It seems rather difficult to work around this problem. Terraform needs to have atomic propositions from the resources it manages. For example: on database X for role Y we have privilege Z. However, in this case privilege Z is actually an alias for a set of privileges (MODIFY, REFERENCE_USAGE, MONITOR, ...). So, when you grant "ALL", the next time the Terraform provider comes along it sees: hey guys, that ALL privilege is not given, I'll do it again.

So, I thought I'd remove the aliases and grant all these privileges individually (instead of using ALL). However, that will not work either. For example, these privileges are inherited. When you grant a privilege Z to role Y, you also grant it to all parents of Y. So, the next time Terraform comes along, it tries very hard to remove these role assignments (in vain).

Perhaps someone with more Snowflake knowledge could chime in, but as far as I can see, the current approach of this provider for granting privileges is not sound. Unless it is rewritten and uses the raw underlying resources as represented in snowflake (or implements all the same logic as Snowflake has), I can't see a way to make this happen.

**Comment by ryanking** [comment]
I think this is "fixed" by removing support for ALL grants. See [this](https://github.com/chanzuckerberg/terraform-provider-snowflake/discussions/318) for discussion.

I am going to close this, please re-open if this re-occurs post upgrading to 0.19.0 and moving away from using ALL grants.
