### ISSUE TITLE
"ALL" privilege no longer works in snowflake_warehouse_grant

### ISSUE THREAD

**Issue by nouafourchette** [chanzuckerberg/terraform-provider-snowflake#371]
**Provider Version**

v0.20.0

**Terraform Version**

v0.12

**Describe the bug**

We updated the provider version from v0.10.0 to v0.20.0, and we started getting error on the existing  snowflake_warehouse_grant that no longer accepts "ALL" as a possible privilege, the possible options are [OWNERSHIP USAGE MODIFY MONITOR OPERATE].

**Expected behavior**

It is absolutely important for us to have "ALL" as a possible privilege in snowflake_warehouse_grant, and in previous versions, it was.

**Code samples and commands**

Terraformed code : 

`
resource "snowflake_warehouse_grant" "warehouse_example_all" {

  warehouse_name = "EXAMPLE_WH"
  privilege      = "ALL"
  roles          = ["SOME_ROLE"]

}
`

The error we get : 
`
Error: expected privilege to be one of [OWNERSHIP USAGE MODIFY MONITOR OPERATE], got ALL
on warehouse_grants.tf line 13, in resource "warehouse_example_all"
13:   privilege      = "ALL"
`

**Comment by ryanking** [comment]
Unfortunately, due to the way ALL grants work in snowflake, there is no sustainable way to support ALL in this provider.

Please see https://github.com/chanzuckerberg/terraform-provider-snowflake/discussions/318 for discussion about this issue and note that we [have some modules](https://github.com/chanzuckerberg/cztack) that will emulate the behavior you want.
