### ISSUE TITLE
Support for Granting privilege X ON ALL <object_type>

### ISSUE THREAD

**Issue by ChrisIsidora** [chanzuckerberg/terraform-provider-snowflake#613]
Support for granting a certain privilege on "all" existing object. For example `grant select on all tables in schema mydb.myschema to role analyst;`

**Describe the solution you'd like**

Introduce either a new resource type or only a new Boolean property on the eligible *_grant resources. This is similar to on_future property the only difference is the Read Method. There needs to be an iteration of the object types. For example for the Read, SELECT privilege ON ALL. You need to get a list of all tables via `SHOW TABLES` and per table (X) you will need to do `SHOW GRANTS ON TABLE X`

**Additional context**

https://docs.snowflake.com/en/sql-reference/sql/grant-privilege.html

**Comment by ChrisIsidora** [comment]
@alldoami What do you think is it better to create a new resource or use existing *_grant resouces?

**Comment by alldoami** [comment]
We have tried to implement the `ALL` grant: https://github.com/chanzuckerberg/cztack/tree/main/snowflake-table-grant-all and other resources are listed there.

**Comment by ChrisIsidora** [comment]
@alldoami That's something different. That's the implementation for when you want to implement ALL privileges to in snowflake. This is the implementation when you want to implement a specific privilege on all specific objects like stated in the description. Ex. A Select grant statement on all existing tables. Please look at https://docs.snowflake.com/en/sql-reference/sql/grant-privilege.html

**Comment by funes79** [comment]
I think the issue is similar to the GRANT ALL (privileges).

The ALL identifier is just a wildcard in Snowflake. There is no easy way to get know whether the resource (the GRANT SELECT/INSERT/UPDATE/whatever ON **ALL**) is in sync with the terraform state. In other words, when you run grant xx on all tables in schema X,  snowflake applies the privilege on the actual list of tables in the given schema and database.
But you cannot get something like "show me roles where ROLE has SELECT ALL on schema X". Snowflake does not provide this kind of functionality. Why? I think because it is just a wildcard, a macro, that in the background runs GRANT SELECT ON TABLE1, TABLE2, TABLE3...  (and these can be hundreds or even thousands of tables).

So if the Snowflake cannot tell us whether the ROLE has or does not have SELECT on ALL tables then we would have to implement such reconciliation. Regarding the terraform state not sure how it would look like - should we write to the tfstate only the fact that it has ALL objects granted or enumerate all objects? This reconciliation would require a scan of the granted tables for the given role and then compare with all the tables in the given schema and database. In this case we would store ALL granted tables (fully qualified names) in the terraform state in (one or multiple) resource(s).  Then in the next terraform run, if there is a new table in a schema, add to the grant resource, and run again GRANT xx on ALL xx. If there is a table granted in the terraform resource but the table does not exists any more, remove it from the state. Not sure if this is really what we want to do 🤔

**Comment by ChrisIsidora** [comment]
@funes79 Hi Tomas,
I do agree with you to some extend but not entirely because the command for granting on all is the same is granting on future which is implemented. The only difference is the read method in which indeed you will need to iteration over the object. When you see that there one object where it's missing this will trigger the grant all on object. When the object (e.g table) is removed from Snowflake there is nothing to do because with the read method you will find out that nothing is missing because that object is removed so there will be no change, the role/user still has grants on all current table. For the future grants we also don't store each object individually. I am half way into implementing this and don't see a problem at the moment unless Im really missing something. The problem with grant all privileges is that you can't query which privileges are available in Snowflake but in our case we can query which object (e.g tables) are there at the moment.

**Comment by ChrisIsidora** [comment]
@alldoami @funes79 Maybe it would be better to keep the consistency of the current grant resource as is. I think it would be better to just create datasources in terraform for the available objects in Snowflake and use that as input to use the grant resources as is. Thanks for thinking along. I will close this feature ticket for now.
